// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUmBDmtGgZ-IbZDyQR03B6cgzmDHgTgM',
    appId: '1:595104681842:web:ae54075909c07b760497eb',
    messagingSenderId: '595104681842',
    projectId: 'bmr-transport',
    authDomain: 'bmr-transport.firebaseapp.com',
    storageBucket: 'bmr-transport.firebasestorage.app',
    measurementId: 'G-9STJ1LDZJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvvZZZ114Hkd0Hsm-eIhIYhpjVFn9ifo',
    appId: '1:595104681842:android:84154b57288246480497eb',
    messagingSenderId: '595104681842',
    projectId: 'bmr-transport',
    storageBucket: 'bmr-transport.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgUmBDmtGgZ-IbZDyQR03B6cgzmDHgTgM',
    appId: '1:595104681842:web:04aa3d14286797e50497eb',
    messagingSenderId: '595104681842',
    projectId: 'bmr-transport',
    authDomain: 'bmr-transport.firebaseapp.com',
    storageBucket: 'bmr-transport.firebasestorage.app',
    measurementId: 'G-PP33H5DCRQ',
  );
}
